# Generated by Django 3.2.5 on 2021-08-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_auto_20210801_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='avr_rating',
            new_name='avg_rating',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='number_ratings',
            new_name='number_rating',
        ),
    ]
