# Generated by Django 3.2.5 on 2021-08-02 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0008_auto_20210802_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watchlist',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='book',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='watchlist_app.onlinelibrary'),
        ),
    ]
